let stockProductos = [
    {id: 1, nombre: "NK65 - MICTLAN EDITION", tipo: "keyboards",desc: "Lorem ipsum dolor sit amet, consectetur adip",precio: 1200, img: './media/keyboard/1kb.jpg'},
    {id: 2, nombre: "NK65 - ALUMINUM EDITION", tipo: "keyboards", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1100, img: './media/keyboard/2kb.jpg'},
    {id: 3, nombre: "NK65 - ENTRY EDITION", tipo: "keyboards", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1200, img: './media/keyboard/3kb.jpg'},
    {id: 4, nombre: "NK65 - SUPERUSER EDITION", tipo: "keyboards", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1400, img: './media/keyboard/4kb.jpg'},
    {id: 5, nombre: "NK87 - ALUMINUM EDITION", tipo: "keyboards", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1200, img: './media/keyboard/5kb.jpg'},
    {id: 6, nombre: "NK87 - ENTRY EDITION", tipo: "keyboards", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1500, img: './media/keyboard/6kb.jpg'},
    {id: 7, nombre: "GMK SPACE CADET II", tipo: "keycaps", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 500, img: './media/keycaps/1kc.jpg'},
    {id: 8, nombre: "HEISENBERG", tipo: "keycaps", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 500, img: './media/keycaps/2kc.jpg'},
    {id: 9, nombre: "CHERRY PBOW", tipo: "keycaps", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 500, img: './media/keycaps/3kc.jpg'},
    {id: 10, nombre: "CHERRY STONE", tipo: "keycaps", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 700, img: './media/keycaps/4kc.jpg'},
    {id: 11, nombre: "GATERON ALUMINUM", tipo: "keycaps", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 700, img: './media/keycaps/5kc.jpg'},
    {id: 12, nombre: "GMK YURI R2", tipo: "keycaps", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 700, img: './media/keycaps/6kc.jpg'},
    {id: 13, nombre: "CHERRY MX BLUE", tipo: "switches", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 900, img: './media/switches/1sw.jpg'},
    {id: 14, nombre: "GATERON CAP YELLOW", tipo: "switches", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1400, img: './media/switches/2sw.jpg'},
    {id: 15, nombre: "GATERON INK - BOX PINK", tipo: "switches", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 7000, img: './media/switches/3sw.jpg'},
    {id: 16, nombre: "KAILH BOX PINK", tipo: "switches", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 777, img: './media/switches/4sw.jpg'},
    {id: 17, nombre: "NK CREAM", tipo: "switches", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 234, img: './media/switches/5sw.jpg'},
    {id: 18, nombre: "NOLIVE - CREAM RECOLOR", tipo: "switches", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 155600, img: './media/switches/6sw.jpg'},
    {id: 20, nombre: "BREAKING BAD", tipo: "deskpads", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 3200, img: './media/deskpads/1dp.jpg'},
    {id: 21, nombre: "DOTS R2", tipo: "deskpads", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 2300, img: './media/deskpads/2dp.jpg'},
    {id: 22, nombre: "MICTLAN", tipo: "deskpads", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 5600, img: './media/deskpads/3dp.jpg'},
    {id: 19, nombre: "MILKSHAKE", tipo: "deskpads", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1600, img: './media/deskpads/4dp.jpg'},
    {id: 23, nombre: "NASA DESKPAD", tipo: "deskpads", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 1700, img: './media/deskpads/5dp.jpg'},
    {id: 24, nombre: "NOTION", tipo: "deskpads", desc: "Lorem ipsum dolor sit amet, consectetur adip", precio: 800, img: './media/deskpads/6dp.jpg'},
]
